DROP TABLE IF EXISTS public.prc;

CREATE TABLE public.prc
(
    capakey character varying(34),
    daa double precision,
    ord character varying(8),
    "in" character varying(4),
    ante character varying(18),
    sl1 character varying(74),
    prc character varying(24),
    na1 character varying(20),
    co1 character varying(20),
    ha1 character varying(16),
    cod1 character varying(50),
    ri1 character varying(50),
    cac character varying(8),
    ddi character varying(4),
    cc character varying(76),
    notif character varying(8),
    caoo character varying(420),
    rscod character varying(20),
    rslt character varying(2),
    rsnr real,
    rspos real,
    acj character varying(8),
    n1 character varying(2),
    tv character varying(2),
    mo character varying(4),
    ha character varying(4),
    pw1 character varying(4),
    sl2 character varying(70),
    pw2 character varying(4),
    na2 character varying(20),
    n2 character varying(2),
    co2 double precision,
    ha2 character varying(16),
    cod2 character varying(4),
    ri2 double precision,
    sl3 character varying(70),
    pw3 character varying(4),
    na3 character varying(20),
    n3 character varying(2),
    co3 double precision,
    ha3 character varying(16),
    cod3 character varying(4),
    ri3 double precision,
    pw4 character varying(4),
    na4 character varying(20),
    n4 character varying(2),
    co4 double precision,
    ha4 character varying(16),
    cod4 character varying(4),
    ri4 double precision,
    na5 character varying(20),
    n5 character varying(2),
    co5 double precision,
    ha5 character varying(16),
    cod5 character varying(4),
    ri5 double precision,
    na6 character varying(20),
    n6 character varying(2),
    co6 double precision,
    ha6 character varying(16),
    cod6 character varying(4),
    ri6 double precision,
    na7 character varying(20),
    n7 character varying(2),
    co7 double precision,
    ha7 character varying(16),
    cod7 character varying(4),
    ri7 double precision,
    na8 character varying(20),
    n8 character varying(2),
    co8 double precision,
    ha8 character varying(16),
    cod8 character varying(4),
    ri8 double precision,
    na9 character varying(20),
    cod9 character varying(4),
    ri9 double precision,
    na10 character varying(20),
    cod10 character varying(4),
    ri10 double precision,
    na11 character varying(20),
    cod11 character varying(4),
    ri11 double precision,
    n14 double precision,
    n56 double precision,
    sheet character varying(12)
);

DROP INDEX IF EXISTS public.prc_capakey_idx;

CREATE INDEX prc_capakey_idx
    ON public.prc USING btree
    (capakey );

DROP INDEX IF EXISTS public.prc_daa_idx;

CREATE INDEX prc_daa_idx
        ON public.prc USING btree
        (daa );
